"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.PRICING_PROVIDER_MULTIPLIERS = exports.PRICING_PROVIDER_ALIASES = exports.PRICING_ENTRIES = void 0;
exports.getPricingEntriesForProvider = getPricingEntriesForProvider;
exports.getCheapestPricingEntry = getCheapestPricingEntry;
const PRICING_SEED_ROWS = [
    {
        providerId: "hostinger",
        displayName: "Hostinger",
        rawPlanLabel: "Shared Single (Entry)",
        normalizedTier: "entry",
        monthlyVisitBaseline: 10_000,
        paidApiBaseline: "no",
        aiUsageBaseline: "no",
        highTrafficRouteBaseline: "/",
        appTypeBaseline: "Small WordPress blog",
        metrics: ["subscription", "bandwidth"],
        approximateRate: "~entry shared hosting pricing",
        sourceUrl: "https://www.hostinger.com/pricing",
        lastVerifiedAt: "2026-03"
    },
    {
        providerId: "hostinger",
        displayName: "Hostinger",
        rawPlanLabel: "Shared Premium",
        normalizedTier: "shared",
        monthlyVisitBaseline: 50_000,
        paidApiBaseline: "no",
        aiUsageBaseline: "no",
        highTrafficRouteBaseline: "/blog/*",
        appTypeBaseline: "Content site",
        metrics: ["subscription", "bandwidth"],
        approximateRate: "~shared hosting pricing",
        sourceUrl: "https://www.hostinger.com/pricing",
        lastVerifiedAt: "2026-03"
    },
    {
        providerId: "hostinger",
        displayName: "Hostinger",
        rawPlanLabel: "Cloud Startup",
        normalizedTier: "cloud",
        monthlyVisitBaseline: 150_000,
        paidApiBaseline: "yes",
        aiUsageBaseline: "no",
        highTrafficRouteBaseline: "/shop/*",
        appTypeBaseline: "Small ecommerce",
        metrics: ["subscription", "bandwidth", "compute"],
        approximateRate: "~cloud hosting pricing",
        sourceUrl: "https://www.hostinger.com/pricing",
        lastVerifiedAt: "2026-03"
    },
    {
        providerId: "hostinger",
        displayName: "Hostinger",
        rawPlanLabel: "Cloud Professional",
        normalizedTier: "cloud",
        monthlyVisitBaseline: 300_000,
        paidApiBaseline: "yes",
        aiUsageBaseline: "yesOften",
        highTrafficRouteBaseline: "/api/v1/orders",
        appTypeBaseline: "Storefront + API",
        metrics: ["subscription", "bandwidth", "compute"],
        approximateRate: "~higher cloud hosting pricing",
        sourceUrl: "https://www.hostinger.com/pricing",
        lastVerifiedAt: "2026-03"
    },
    {
        providerId: "bluehost",
        displayName: "Bluehost",
        rawPlanLabel: "Basic Shared",
        normalizedTier: "entry",
        monthlyVisitBaseline: 15_000,
        paidApiBaseline: "no",
        aiUsageBaseline: "no",
        highTrafficRouteBaseline: "/",
        appTypeBaseline: "Basic WP site",
        metrics: ["subscription", "bandwidth"],
        approximateRate: "~entry shared hosting pricing",
        sourceUrl: "https://www.bluehost.com/pricing",
        lastVerifiedAt: "2026-03"
    },
    {
        providerId: "bluehost",
        displayName: "Bluehost",
        rawPlanLabel: "Choice Plus",
        normalizedTier: "sharedPlus",
        monthlyVisitBaseline: 120_000,
        paidApiBaseline: "yes",
        aiUsageBaseline: "no",
        highTrafficRouteBaseline: "/store/*",
        appTypeBaseline: "Store + blog",
        metrics: ["subscription", "bandwidth"],
        approximateRate: "~premium shared hosting pricing",
        sourceUrl: "https://www.bluehost.com/pricing",
        lastVerifiedAt: "2026-03"
    },
    {
        providerId: "bluehost",
        displayName: "Bluehost",
        rawPlanLabel: "Online Store Pro",
        normalizedTier: "managed",
        monthlyVisitBaseline: 250_000,
        paidApiBaseline: "yes",
        aiUsageBaseline: "yesOften",
        highTrafficRouteBaseline: "/checkout",
        appTypeBaseline: "WooCommerce store",
        metrics: ["subscription", "bandwidth", "transactionFees"],
        approximateRate: "~managed ecommerce hosting pricing",
        sourceUrl: "https://www.bluehost.com/pricing",
        lastVerifiedAt: "2026-03"
    },
    {
        providerId: "ionos",
        displayName: "IONOS",
        rawPlanLabel: "Essential Shared",
        normalizedTier: "entry",
        monthlyVisitBaseline: 12_000,
        paidApiBaseline: "no",
        aiUsageBaseline: "no",
        highTrafficRouteBaseline: "/",
        appTypeBaseline: "Brochure site",
        metrics: ["subscription", "bandwidth"],
        approximateRate: "~entry shared hosting pricing",
        sourceUrl: "https://www.ionos.com/hosting/web-hosting",
        lastVerifiedAt: "2026-03"
    },
    {
        providerId: "ionos",
        displayName: "IONOS",
        rawPlanLabel: "VPS L",
        normalizedTier: "vpsMedium",
        monthlyVisitBaseline: 350_000,
        paidApiBaseline: "yes",
        aiUsageBaseline: "yesOften",
        highTrafficRouteBaseline: "/api/v1/*",
        appTypeBaseline: "Custom web app",
        metrics: ["subscription", "compute", "bandwidth"],
        approximateRate: "~mid VPS pricing",
        sourceUrl: "https://www.ionos.com/servers/vps",
        lastVerifiedAt: "2026-03"
    },
    {
        providerId: "dreamhost",
        displayName: "DreamHost",
        rawPlanLabel: "Shared Launch",
        normalizedTier: "entry",
        monthlyVisitBaseline: 20_000,
        paidApiBaseline: "no",
        aiUsageBaseline: "no",
        highTrafficRouteBaseline: "/",
        appTypeBaseline: "Personal site",
        metrics: ["subscription", "bandwidth"],
        approximateRate: "~entry shared hosting pricing",
        sourceUrl: "https://www.dreamhost.com/hosting/shared/",
        lastVerifiedAt: "2026-03"
    },
    {
        providerId: "dreamhost",
        displayName: "DreamHost",
        rawPlanLabel: "Managed WP Pro",
        normalizedTier: "managed",
        monthlyVisitBaseline: 400_000,
        paidApiBaseline: "yes",
        aiUsageBaseline: "yesOften",
        highTrafficRouteBaseline: "/wp-json/*",
        appTypeBaseline: "High-traffic WP",
        metrics: ["subscription", "bandwidth", "compute"],
        approximateRate: "~managed WordPress pricing",
        sourceUrl: "https://www.dreamhost.com/wordpress/managed-wp-hosting/",
        lastVerifiedAt: "2026-03"
    },
    {
        providerId: "siteground",
        displayName: "SiteGround",
        rawPlanLabel: "StartUp",
        normalizedTier: "entry",
        monthlyVisitBaseline: 25_000,
        paidApiBaseline: "no",
        aiUsageBaseline: "no",
        highTrafficRouteBaseline: "/",
        appTypeBaseline: "Small business site",
        metrics: ["subscription", "bandwidth"],
        approximateRate: "~entry managed hosting pricing",
        sourceUrl: "https://www.siteground.com/web-hosting.htm",
        lastVerifiedAt: "2026-03"
    },
    {
        providerId: "siteground",
        displayName: "SiteGround",
        rawPlanLabel: "Cloud 4 CPU",
        normalizedTier: "cloud",
        monthlyVisitBaseline: 500_000,
        paidApiBaseline: "yes",
        aiUsageBaseline: "yesOften",
        highTrafficRouteBaseline: "/api/internal/*",
        appTypeBaseline: "SaaS backend",
        metrics: ["subscription", "bandwidth", "compute"],
        approximateRate: "~cloud hosting pricing",
        sourceUrl: "https://www.siteground.com/cloud-hosting.htm",
        lastVerifiedAt: "2026-03"
    },
    {
        providerId: "hostgator",
        displayName: "HostGator",
        rawPlanLabel: "Hatchling",
        normalizedTier: "entry",
        monthlyVisitBaseline: 15_000,
        paidApiBaseline: "no",
        aiUsageBaseline: "no",
        highTrafficRouteBaseline: "/",
        appTypeBaseline: "Simple WP site",
        metrics: ["subscription", "bandwidth"],
        approximateRate: "~entry shared hosting pricing",
        sourceUrl: "https://www.hostgator.com/web-hosting",
        lastVerifiedAt: "2026-03"
    },
    {
        providerId: "hostgator",
        displayName: "HostGator",
        rawPlanLabel: "VPS Snappy 4000",
        normalizedTier: "vpsMedium",
        monthlyVisitBaseline: 380_000,
        paidApiBaseline: "yes",
        aiUsageBaseline: "yesOften",
        highTrafficRouteBaseline: "/api/v1/payments",
        appTypeBaseline: "App backend",
        metrics: ["subscription", "compute", "bandwidth"],
        approximateRate: "~mid VPS pricing",
        sourceUrl: "https://www.hostgator.com/vps-hosting",
        lastVerifiedAt: "2026-03"
    },
    {
        providerId: "godaddy",
        displayName: "GoDaddy",
        rawPlanLabel: "Economy",
        normalizedTier: "entry",
        monthlyVisitBaseline: 20_000,
        paidApiBaseline: "no",
        aiUsageBaseline: "no",
        highTrafficRouteBaseline: "/",
        appTypeBaseline: "Small brochure site",
        metrics: ["subscription", "bandwidth"],
        approximateRate: "~entry shared hosting pricing",
        sourceUrl: "https://www.godaddy.com/hosting/web-hosting",
        lastVerifiedAt: "2026-03"
    },
    {
        providerId: "godaddy",
        displayName: "GoDaddy",
        rawPlanLabel: "Business Hosting Expand",
        normalizedTier: "cloud",
        monthlyVisitBaseline: 420_000,
        paidApiBaseline: "yes",
        aiUsageBaseline: "yesOften",
        highTrafficRouteBaseline: "/api/cart/*",
        appTypeBaseline: "Storefront API",
        metrics: ["subscription", "bandwidth", "compute"],
        approximateRate: "~business hosting pricing",
        sourceUrl: "https://www.godaddy.com/hosting/business-hosting",
        lastVerifiedAt: "2026-03"
    },
    {
        providerId: "a2",
        displayName: "A2 Hosting",
        rawPlanLabel: "Startup",
        normalizedTier: "entry",
        monthlyVisitBaseline: 20_000,
        paidApiBaseline: "no",
        aiUsageBaseline: "no",
        highTrafficRouteBaseline: "/",
        appTypeBaseline: "Dev/test site",
        metrics: ["subscription", "bandwidth"],
        approximateRate: "~entry shared hosting pricing",
        sourceUrl: "https://www.a2hosting.com/web-hosting",
        lastVerifiedAt: "2026-03"
    },
    {
        providerId: "a2",
        displayName: "A2 Hosting",
        rawPlanLabel: "Managed VPS Power",
        normalizedTier: "vpsLarge",
        monthlyVisitBaseline: 500_000,
        paidApiBaseline: "yes",
        aiUsageBaseline: "yesOften",
        highTrafficRouteBaseline: "/api/v2/*",
        appTypeBaseline: "High-traffic API",
        metrics: ["subscription", "compute", "bandwidth"],
        approximateRate: "~managed VPS pricing",
        sourceUrl: "https://www.a2hosting.com/vps-hosting/managed",
        lastVerifiedAt: "2026-03"
    },
    {
        providerId: "inmotion",
        displayName: "InMotion",
        rawPlanLabel: "Core Shared",
        normalizedTier: "entry",
        monthlyVisitBaseline: 25_000,
        paidApiBaseline: "no",
        aiUsageBaseline: "no",
        highTrafficRouteBaseline: "/",
        appTypeBaseline: "Business site",
        metrics: ["subscription", "bandwidth"],
        approximateRate: "~entry shared hosting pricing",
        sourceUrl: "https://www.inmotionhosting.com/shared-hosting",
        lastVerifiedAt: "2026-03"
    },
    {
        providerId: "inmotion",
        displayName: "InMotion",
        rawPlanLabel: "VPS 4GB RAM",
        normalizedTier: "vpsMedium",
        monthlyVisitBaseline: 520_000,
        paidApiBaseline: "yes",
        aiUsageBaseline: "yesOften",
        highTrafficRouteBaseline: "/api/orders/*",
        appTypeBaseline: "Order system",
        metrics: ["subscription", "compute", "bandwidth"],
        approximateRate: "~mid VPS pricing",
        sourceUrl: "https://www.inmotionhosting.com/vps-hosting",
        lastVerifiedAt: "2026-03"
    },
    {
        providerId: "digitalocean",
        displayName: "DigitalOcean",
        rawPlanLabel: "Droplet 1vCPU/1GB",
        normalizedTier: "vpsSmall",
        monthlyVisitBaseline: 150_000,
        paidApiBaseline: "yes",
        aiUsageBaseline: "no",
        highTrafficRouteBaseline: "/app/*",
        appTypeBaseline: "Custom app",
        metrics: ["subscription", "compute", "bandwidth"],
        approximateRate: "~small droplet pricing",
        sourceUrl: "https://www.digitalocean.com/pricing/droplets",
        lastVerifiedAt: "2026-03"
    },
    {
        providerId: "digitalocean",
        displayName: "DigitalOcean",
        rawPlanLabel: "App Platform Pro",
        normalizedTier: "appPlatform",
        monthlyVisitBaseline: 700_000,
        paidApiBaseline: "yes",
        aiUsageBaseline: "yesOften",
        highTrafficRouteBaseline: "/realtime/*",
        appTypeBaseline: "Real-time app",
        metrics: ["subscription", "compute", "bandwidth"],
        approximateRate: "~app platform pricing",
        sourceUrl: "https://www.digitalocean.com/pricing/app-platform",
        lastVerifiedAt: "2026-03"
    },
    {
        providerId: "linode",
        displayName: "Linode",
        rawPlanLabel: "Nanode 1GB",
        normalizedTier: "vpsSmall",
        monthlyVisitBaseline: 140_000,
        paidApiBaseline: "yes",
        aiUsageBaseline: "no",
        highTrafficRouteBaseline: "/",
        appTypeBaseline: "Single-app server",
        metrics: ["subscription", "compute", "bandwidth"],
        approximateRate: "~small VPS pricing",
        sourceUrl: "https://www.linode.com/pricing/",
        lastVerifiedAt: "2026-03"
    },
    {
        providerId: "linode",
        displayName: "Linode",
        rawPlanLabel: "8GB",
        normalizedTier: "vpsLarge",
        monthlyVisitBaseline: 800_000,
        paidApiBaseline: "yes",
        aiUsageBaseline: "yesOften",
        highTrafficRouteBaseline: "/services/*",
        appTypeBaseline: "Multi-tenant SaaS",
        metrics: ["subscription", "compute", "bandwidth"],
        approximateRate: "~large VPS pricing",
        sourceUrl: "https://www.linode.com/pricing/",
        lastVerifiedAt: "2026-03"
    },
    {
        providerId: "vultr",
        displayName: "Vultr",
        rawPlanLabel: "Cloud Compute 1vCPU",
        normalizedTier: "vpsSmall",
        monthlyVisitBaseline: 130_000,
        paidApiBaseline: "yes",
        aiUsageBaseline: "no",
        highTrafficRouteBaseline: "/",
        appTypeBaseline: "Monolith app",
        metrics: ["subscription", "compute", "bandwidth"],
        approximateRate: "~small cloud compute pricing",
        sourceUrl: "https://www.vultr.com/pricing/",
        lastVerifiedAt: "2026-03"
    },
    {
        providerId: "vultr",
        displayName: "Vultr",
        rawPlanLabel: "High-Freq 4vCPU",
        normalizedTier: "vpsLarge",
        monthlyVisitBaseline: 750_000,
        paidApiBaseline: "yes",
        aiUsageBaseline: "yesOften",
        highTrafficRouteBaseline: "/search/*",
        appTypeBaseline: "Search-heavy app",
        metrics: ["subscription", "compute", "bandwidth"],
        approximateRate: "~high-frequency compute pricing",
        sourceUrl: "https://www.vultr.com/pricing/",
        lastVerifiedAt: "2026-03"
    },
    {
        providerId: "aws",
        displayName: "AWS",
        rawPlanLabel: "CloudFront (CDN)",
        normalizedTier: "usage",
        monthlyVisitBaseline: 350_000,
        paidApiBaseline: "yes",
        aiUsageBaseline: "no",
        highTrafficRouteBaseline: "/assets/*",
        appTypeBaseline: "CDN-backed route",
        metrics: ["bandwidth", "requests"],
        approximateRate: "~$0.085/GB transfer baseline",
        sourceUrl: "https://aws.amazon.com/cloudfront/pricing/",
        lastVerifiedAt: "2026-03"
    },
    {
        providerId: "aws",
        displayName: "AWS",
        rawPlanLabel: "EC2 t3.small",
        normalizedTier: "vpsSmall",
        monthlyVisitBaseline: 350_000,
        paidApiBaseline: "yes",
        aiUsageBaseline: "yesOften",
        highTrafficRouteBaseline: "/api/*",
        appTypeBaseline: "Backend API",
        metrics: ["subscription", "compute", "bandwidth"],
        approximateRate: "~small EC2 baseline",
        sourceUrl: "https://aws.amazon.com/ec2/pricing/",
        lastVerifiedAt: "2026-03"
    },
    {
        providerId: "aws",
        displayName: "AWS",
        rawPlanLabel: "ECS/Fargate Cluster",
        normalizedTier: "cluster",
        monthlyVisitBaseline: 2_000_000,
        paidApiBaseline: "yes",
        aiUsageBaseline: "yesOften",
        highTrafficRouteBaseline: "/micro/*",
        appTypeBaseline: "Microservices app",
        metrics: ["compute", "requests", "bandwidth"],
        approximateRate: "~container cluster pricing",
        sourceUrl: "https://aws.amazon.com/fargate/pricing/",
        lastVerifiedAt: "2026-03"
    },
    {
        providerId: "gcp",
        displayName: "Google Cloud",
        rawPlanLabel: "Cloud Run 1 vCPU",
        normalizedTier: "container",
        monthlyVisitBaseline: 800_000,
        paidApiBaseline: "yes",
        aiUsageBaseline: "yesOften",
        highTrafficRouteBaseline: "/service/*",
        appTypeBaseline: "Container API",
        metrics: ["compute", "requests", "bandwidth"],
        approximateRate: "~container request pricing",
        sourceUrl: "https://cloud.google.com/run/pricing",
        lastVerifiedAt: "2026-03"
    },
    {
        providerId: "azure",
        displayName: "Azure",
        rawPlanLabel: "P1v3 App Service",
        normalizedTier: "appPlatform",
        monthlyVisitBaseline: 400_000,
        paidApiBaseline: "yes",
        aiUsageBaseline: "yesOften",
        highTrafficRouteBaseline: "/api/*",
        appTypeBaseline: "Production API",
        metrics: ["subscription", "compute", "bandwidth"],
        approximateRate: "~App Service pricing",
        sourceUrl: "https://azure.microsoft.com/pricing/details/app-service/windows/",
        lastVerifiedAt: "2026-03"
    },
    {
        providerId: "azure",
        displayName: "Azure",
        rawPlanLabel: "AKS Small Cluster",
        normalizedTier: "cluster",
        monthlyVisitBaseline: 1_200_000,
        paidApiBaseline: "yes",
        aiUsageBaseline: "yesOften",
        highTrafficRouteBaseline: "/svc/*",
        appTypeBaseline: "Kubernetes microservices",
        metrics: ["compute", "bandwidth", "requests"],
        approximateRate: "~cluster pricing",
        sourceUrl: "https://azure.microsoft.com/pricing/details/kubernetes-service/",
        lastVerifiedAt: "2026-03"
    },
    {
        providerId: "heroku",
        displayName: "Heroku",
        rawPlanLabel: "Hobby",
        normalizedTier: "entry",
        monthlyVisitBaseline: 25_000,
        paidApiBaseline: "no",
        aiUsageBaseline: "no",
        highTrafficRouteBaseline: "/",
        appTypeBaseline: "Prototype app",
        metrics: ["subscription", "compute"],
        approximateRate: "~entry dyno pricing",
        sourceUrl: "https://www.heroku.com/pricing",
        lastVerifiedAt: "2026-03"
    },
    {
        providerId: "heroku",
        displayName: "Heroku",
        rawPlanLabel: "Standard-2x",
        normalizedTier: "appPlatform",
        monthlyVisitBaseline: 260_000,
        paidApiBaseline: "yes",
        aiUsageBaseline: "yesOften",
        highTrafficRouteBaseline: "/jobs/*",
        appTypeBaseline: "Worker-heavy app",
        metrics: ["subscription", "compute"],
        approximateRate: "~app dyno pricing",
        sourceUrl: "https://www.heroku.com/pricing",
        lastVerifiedAt: "2026-03"
    },
    {
        providerId: "cloudflare",
        displayName: "Cloudflare",
        rawPlanLabel: "Pro",
        normalizedTier: "subscription",
        monthlyVisitBaseline: 100_000,
        paidApiBaseline: "yes",
        aiUsageBaseline: "no",
        highTrafficRouteBaseline: "/",
        appTypeBaseline: "CDN-backed route",
        metrics: ["subscription", "workers", "bandwidth"],
        approximateRate: "~$20/month plus Workers usage",
        sourceUrl: "https://www.cloudflare.com/plans/",
        lastVerifiedAt: "2026-03"
    },
    {
        providerId: "vercel",
        displayName: "Vercel",
        rawPlanLabel: "Pro",
        normalizedTier: "subscription",
        monthlyVisitBaseline: 120_000,
        paidApiBaseline: "yes",
        aiUsageBaseline: "yesOften",
        highTrafficRouteBaseline: "/",
        appTypeBaseline: "Production frontend app",
        metrics: ["subscription", "bandwidth", "compute"],
        approximateRate: "~$20/month plus usage",
        sourceUrl: "https://vercel.com/pricing",
        lastVerifiedAt: "2026-03"
    },
    {
        providerId: "netlify",
        displayName: "Netlify",
        rawPlanLabel: "Pro",
        normalizedTier: "subscription",
        monthlyVisitBaseline: 100_000,
        paidApiBaseline: "yes",
        aiUsageBaseline: "no",
        highTrafficRouteBaseline: "/",
        appTypeBaseline: "Production web app",
        metrics: ["subscription", "bandwidth", "compute", "buildMinutes"],
        approximateRate: "~$19/month plus usage",
        sourceUrl: "https://www.netlify.com/pricing/",
        lastVerifiedAt: "2026-03"
    },
    {
        providerId: "supabase",
        displayName: "Supabase",
        rawPlanLabel: "Pro",
        normalizedTier: "subscription",
        monthlyVisitBaseline: 120_000,
        paidApiBaseline: "yes",
        aiUsageBaseline: "no",
        highTrafficRouteBaseline: "/api/*",
        appTypeBaseline: "Backend + database",
        metrics: ["subscription", "database", "bandwidth", "authUsers"],
        approximateRate: "~$25/month plus usage",
        sourceUrl: "https://supabase.com/pricing",
        lastVerifiedAt: "2026-03"
    },
    {
        providerId: "openai",
        displayName: "OpenAI",
        rawPlanLabel: "API Usage",
        normalizedTier: "usage",
        monthlyVisitBaseline: 100_000,
        paidApiBaseline: "yes",
        aiUsageBaseline: "yesOften",
        highTrafficRouteBaseline: "/ai/*",
        appTypeBaseline: "AI app",
        metrics: ["inputTokens", "outputTokens"],
        approximateRate: "~model-dependent token pricing",
        sourceUrl: "https://platform.openai.com/pricing",
        lastVerifiedAt: "2026-03"
    },
    {
        providerId: "anthropic",
        displayName: "Anthropic",
        rawPlanLabel: "Claude API",
        normalizedTier: "usage",
        monthlyVisitBaseline: 100_000,
        paidApiBaseline: "yes",
        aiUsageBaseline: "yesOften",
        highTrafficRouteBaseline: "/ai/*",
        appTypeBaseline: "AI app",
        metrics: ["inputTokens", "outputTokens"],
        approximateRate: "~model-dependent token pricing",
        sourceUrl: "https://www.anthropic.com/pricing",
        lastVerifiedAt: "2026-03"
    },
    {
        providerId: "shopify",
        displayName: "Shopify",
        rawPlanLabel: "Basic",
        normalizedTier: "subscription",
        monthlyVisitBaseline: 120_000,
        paidApiBaseline: "yes",
        aiUsageBaseline: "no",
        highTrafficRouteBaseline: "/checkout",
        appTypeBaseline: "Storefront",
        metrics: ["subscription", "transactionFees"],
        approximateRate: "~$39/month plus transaction fees",
        sourceUrl: "https://www.shopify.com/pricing",
        lastVerifiedAt: "2026-03"
    }
];
exports.PRICING_ENTRIES = PRICING_SEED_ROWS;
exports.PRICING_PROVIDER_ALIASES = {
    hostinger: "hostinger",
    bluehost: "bluehost",
    ionos: "ionos",
    dreamhost: "dreamhost",
    siteground: "siteground",
    hostgator: "hostgator",
    godaddy: "godaddy",
    a2: "a2",
    inmotion: "inmotion",
    digitalocean: "digitalocean",
    linode: "linode",
    vultr: "vultr",
    aws: "aws",
    gcp: "gcp",
    azure: "azure",
    heroku: "heroku",
    vercel: "vercel",
    netlify: "netlify",
    cloudflare: "cloudflare",
    supabase: "supabase",
    openai: "openai",
    anthropic: "anthropic",
    shopify: "shopify",
    cloudfront: "aws",
    "aws-s3": "aws",
    "aws-api-gateway": "aws",
    "cloudflare-cdn": "cloudflare",
    "vercel-edge": "vercel",
    render: null,
    railway: null,
    other: null
};
exports.PRICING_PROVIDER_MULTIPLIERS = {
    hostinger: 0.82,
    bluehost: 0.85,
    ionos: 0.88,
    dreamhost: 0.9,
    siteground: 0.94,
    hostgator: 0.88,
    godaddy: 0.9,
    a2: 0.92,
    inmotion: 0.93,
    digitalocean: 1.02,
    linode: 0.98,
    vultr: 1,
    aws: 1.05,
    gcp: 1.04,
    azure: 1.03,
    heroku: 1.08,
    vercel: 1.12,
    netlify: 1.08,
    cloudflare: 0.96,
    supabase: 1.02,
    openai: 1.22,
    anthropic: 1.2,
    shopify: 1.04
};
function getPricingEntriesForProvider(providerId) {
    return exports.PRICING_ENTRIES.filter((entry) => entry.providerId === providerId);
}
function getCheapestPricingEntry(providerId) {
    return getPricingEntriesForProvider(providerId)[0] ?? null;
}
